project:
  type: website
  output-dir: docs

website:
  title: "baqapp"
  sidebar:
    style: "docked"
    search: true
    contents:
      - text: Introduction
        href: index.qmd
      - text: "Data Exploration (TODO)"
        href: data-exploration.qmd
      - text: "Methodology (TODO)"
        href: methodology.qmd
      - text: "Results (TODO)"
        href: results.qmd
      - text: "Conclusion (TODO)"
        href: conclusion.qmd

format:
  html:
    theme: cosmo
    css: styles.css
    toc: true



