project:
  type: website
  output-dir: docs

website:
  title: "baqapp"
  sidebar:
    style: "docked"
    search: true
    contents:
      - text: Introduction
        href: index.qmd
      - text: "Data Exploration"
        href: data-exploration.qmd
      - text: "Methodology & Results"
        href: methodology.qmd
      - text: "Dashboard Presentation"
        href: dashboard.qmd

format:
  html:
    theme: darkly
    css: styles.css
    toc: true



